### ISSUE TITLE
Update GSL dependency

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/outbreaker#3]
From B Ripley:
Prof Brian Ripley ripley@stats.ox.ac.uk

11:55 AM (2 hours ago)

to Robin, Michael, me, Richard, Steffen, CRAN
GNU GSL moved to version 2.0 this year, and 2.1 is current.  Some of your packages do not work with current versions ...

VBLPCM gsl outbreaker:
configure: error: Need GSL version >= 1.12

diversitree:
checking if GSL version >= 1.15... configure: error: Need GSL version >= 1.15

libamtrack:
checking if GSL version >= 1.8... configure: error: Need GSL version >= 1.8

Please correct these and other problems showing on the CRAN check packages for your packages.  In the case of outbreaker you also need to declare GSL in SystemRequirements!

**Comment by thibautjombart** [comment]
@richfitz would it be time to replace dependency on GSL with dependency on R internals? How painful would you expect this to be? I'm essentially using random number generation and probability density functions, as far as I remember.

**Comment by richfitz** [comment]
Those are easy enough to change out.  I can take a look if you'd like.

**Comment by thibautjombart** [comment]
Sure, would be great! I think if you find-grep-dired for 'gsl_' in the /src you'll find all relevant instances.

**Comment by richfitz** [comment]
Not in the R API last time I looked, but easy to implement:
- `gsl_ran_shuffle`
- `gsl_ran_sample`
- `gsl_ran_choose`

The rest look pretty straightforward.

However, deciding if the change works is hard, because there's (a) no test suite and (b) the stochastic draws will change as the random number generation will differ.

It might be worth thinking about what you're going to do with outbreaker2 and perhaps just fix the simple version problem for now?

**Comment by thibautjombart** [comment]
Agreed, but thanks for looking into it!

**Comment by thibautjombart** [comment]
Done as of a4812b9eddbe70023839439bd81e29642007793c
